////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./toplevel.v
// {{{
// Project:	10Gb Ethernet switch
//
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga -I .: -d -o . allclocks.txt siclk.txt sirefclk.txt global.txt wbdown.txt icape.txt version.txt pwrcount.txt rtccount.txt gpio.txt spio.txt wbuconsole.txt zipmaster.txt bkram.txt ddr3.txt flash.txt sdio.txt emmc.txt sata.txt sdslave.txt netrouter.txt cpunet.txt netstats.txt hdmi.txt cec.txt edid.txt routescope.txt i2cscope.txt gatescope.txt netscope.txt satascope.txt sdioscope.txt emmcscope.txt flashscope.txt mem_bkram_only.txt mem_full.txt mem_flash_bkram.txt i2ccpu.txt fan.txt sirefclkcounter.txt netclk.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2023-2026, Gisselquist Technology, LLC
// {{{
// This file is part of the ETH10G project.
//
// The ETH10G project contains free software and gateware, licensed under the
// terms of the 3rd version of the GNU General Public License as published by
// the Free Software Foundation.
//
// This project is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
// }}}
// License:	GPL, v3, as defined and found on www.gnu.org,
// {{{
//		http://www.gnu.org/licenses/gpl.html
//
////////////////////////////////////////////////////////////////////////////////
//
// }}}
`default_nettype	none


//
// Here we declare our toplevel.v (toplevel) design module.
// All design logic must take place beneath this top level.
//
// The port declarations just copy data from the @TOP.PORTLIST
// key, or equivalently from the @MAIN.PORTLIST key if
// @TOP.PORTLIST is absent.  For those peripherals that don't need
// any top level logic, the @MAIN.PORTLIST should be sufficent,
// so the @TOP.PORTLIST key may be left undefined.
//
// The only exception is that any clocks with CLOCK.TOP tags will
// also appear in this list
//
module	toplevel(
			io_temp_sda, io_temp_scl,
			o_fan_pwm, o_fan_sys, i_fan_tach,
			io_i2c_sda, io_i2c_scl,
			o_i2c_mxrst_n,
		// cec ports
		io_hdmirx_cec, io_hdmitx_cec,
			i_gnet_los, o_gnettx_disable,
			o_gnet_linkup, o_gnet_activity,
			o_gnet_p, o_gnet_n,
			i_gnet_p, i_gnet_n,
			i_clk_156mhz_p, i_clk_156mhz_n,
		// SPIO interface
		i_sw, i_nbtn_u, i_nbtn_l, i_nbtn_c, i_nbtn_r, i_nbtn_d, o_led,
			io_hdmirx_scl, io_hdmirx_sda,
		io_siref_clk_p, io_siref_clk_n,
		i_clk_si_p, i_clk_si_n,
		i_clk_200mhz_p, i_clk_200mhz_n,
		// UART/host to wishbone interface
		i_wbu_uart_rx, o_wbu_uart_tx,
		o_wbu_uart_cts_n,
		i_hdmirx_clk_p, i_hdmirx_clk_n,
		i_hdmirx_p, i_hdmirx_n,
		o_hdmitx_clk_p, o_hdmitx_clk_n,
		o_hdmitx_p, o_hdmitx_n,
		// Top level Quad-SPI I/O ports
		o_flash_sck, o_flash_cs_n, io_flash_dat,
		// GPIO ports
		i_pi_reset_n, i_soft_reset, i_hdmitx_hpd_n,
		o_tp, o_si5324_rst, i_si5324_int,
		o_hdmirx_hpd_n,
		// SDIO SD Card

o_sdcard_clk,
i_sdcard_cd_n,

		io_sdcard_cmd, io_sdcard_dat,
		// eMMC Card

		o_emmc_clk,


		i_emmc_ds,

		io_emmc_cmd, io_emmc_dat,
		i_sdslav_clk,
		io_sdslav_cmd,
		io_sdslav_dat,
		// DDR3 I/O port wires
		o_ddr3_reset_n, o_ddr3_cke, o_ddr3_clk_p, o_ddr3_clk_n,
		o_ddr3_s_n, o_ddr3_ras_n, o_ddr3_cas_n, o_ddr3_we_n,
		o_ddr3_ba, o_ddr3_a,
		o_ddr3_odt, o_ddr3_dm,
		io_ddr3_dqs_p, io_ddr3_dqs_n, io_ddr3_dq,
		i_sata_p, i_sata_n, o_sata_p, o_sata_n,
		i_clk_150mhz_p, i_clk_150mhz_n);
	//
	// Declaring any top level parameters.
	//
	// These declarations just copy data from the @TOP.PARAM key,
	// or from the @MAIN.PARAM key if @TOP.PARAM is absent.  For
	// those peripherals that don't do anything at the top level,
	// the @MAIN.PARAM key should be sufficient, so the @TOP.PARAM
	// key may be left undefined.
	//
	localparam	NETDEVS  = 4;
`ifdef	CPUNET_ACCESS
	localparam	NETPORTS = 4+1;
`else
	localparam	NETPORTS = 4;
`endif
	localparam	ICAPE_LGDIV=3;
	////////////////////////////////////////////////////////////////////////
	//
	// Variables/definitions/parameters used by the ZipCPU bus master
	// {{{
	//
	// A 32-bit address indicating where the ZipCPU should start running
	// from
`ifdef	BKROM_ACCESS
	localparam	RESET_ADDRESS = @$(/bkrom.BASE);
`else
`ifdef	FLASH_ACCESS
	localparam	RESET_ADDRESS = 115343360;
`else
	localparam	RESET_ADDRESS = 67108864;
`endif	// FLASH_ACCESS
`endif	// BKROM_ACCESS
	//
	// The number of valid bits on the bus
	localparam	ZIP_ADDRESS_WIDTH = 25; // Zip-CPU address width
	//
	// Number of ZipCPU interrupts
	localparam	ZIP_INTS = 16;
	//
	// ZIP_START_HALTED
	//
	// A boolean, indicating whether or not the ZipCPU be halted on startup?
`ifdef	BKROM_ACCESS
	localparam	ZIP_START_HALTED=1'b0;
`else
	localparam	ZIP_START_HALTED=1'b1;
`endif
	// }}}
	////////////////////////////////////////////////////////////////////////
	//
	// WBUBUS parameters
	// {{{
	// Baudrate :   1000000
	// Clock    : 100000000
	localparam [23:0] BUSUART = 24'h64;	//   1000000 baud
	localparam	DBGBUSBITS = $clog2(BUSUART);
	//
	// Maximum command is 6 bytes, where each byte takes 10 baud clocks
	// and each baud clock requires DBGBUSBITS to represent.  Here,
	// we'll add one more for good measure.
	localparam	DBGBUSWATCHDOG_RAW = DBGBUSBITS + 9;
	localparam	DBGBUSWATCHDOG = (DBGBUSWATCHDOG_RAW > 19)
				? DBGBUSWATCHDOG_RAW : 19;
	// }}}
	localparam DDR3_CONTROLLERCONTROLLER_CLK_PERIOD = 10_000,  //ps, clock period of the controller interface
		DDR3_CLK_PERIOD = 2_500; //ps, clock period of the DDR3 RAM device (must be 1/4 of the CONTROLLER_CLK_PERIOD) 
	localparam DDR3_CONTROLLERROW_BITS = 14,  // width of row address
		DDR3_CONTROLLERCOL_BITS = 10,  // width of column address
		DDR3_CONTROLLERBA_BITS  =  3,  // width of bank address
		DDR3_CONTROLLERDQ_BITS  =  8,  // Size of one octet
		DDR3_CONTROLLERBYTE_LANES = 8, //8 lanes of DQ
		DDR3_CONTROLLERAUX_WIDTH = 16, //width of aux line (must be >= 4) 
		DDR3_CONTROLLERSERDES_RATIO = $rtoi(DDR3_CONTROLLERCONTROLLER_CLK_PERIOD/DDR3_CLK_PERIOD),
		//4 is the width of a single ddr3 command {cs_n, ras_n, cas_n, we_n} plus 3 (ck_en, odt, reset_n) plus bank bits plus row bits
		DDR3_CONTROLLERCMD_LEN = 4 + 3 + DDR3_CONTROLLERBA_BITS + DDR3_CONTROLLERROW_BITS;


	//
	// Declaring our input and output ports.  We listed these above,
	// now we are declaring them here.
	//
	// These declarations just copy data from the @TOP.IODECLS key,
	// or from the @MAIN.IODECL key if @TOP.IODECL is absent.  For
	// those peripherals that don't do anything at the top level,
	// the @MAIN.IODECL key should be sufficient, so the @TOP.IODECL
	// key may be left undefined.
	//
	// We start with any @CLOCK.TOP keys
	//
	inout	wire	io_temp_sda, io_temp_scl;
	output	wire	o_fan_pwm, o_fan_sys;
	input	wire	i_fan_tach;
	inout	wire	io_i2c_sda, io_i2c_scl;
	output	wire	o_i2c_mxrst_n;
	// CEC wires
	inout	wire		io_hdmirx_cec, io_hdmitx_cec;
	// 10Gb Ethernet
	input	wire	[4-1:0]	i_gnet_los;
	output	wire	[4-1:0]	o_gnettx_disable;
	output	wire	[4-1:0]	o_gnet_linkup;
	output	wire	[4-1:0]	o_gnet_activity;
	output	wire	[4-1:0]	o_gnet_p, o_gnet_n;
	input	wire	[4-1:0]	i_gnet_p, i_gnet_n;
	input	wire			i_clk_156mhz_p, i_clk_156mhz_n;
	// SPIO interface
	input	wire	[4-1:0]	i_sw;
	input	wire	i_nbtn_c, i_nbtn_d, i_nbtn_l, i_nbtn_r, i_nbtn_u;
	output	wire	[8-1:0]	o_led;
	inout	wire	io_hdmirx_scl, io_hdmirx_sda;
	inout	wire	io_siref_clk_p, io_siref_clk_n;
	input	wire	i_clk_si_p, i_clk_si_n;
	input	wire	i_clk_200mhz_p, i_clk_200mhz_n;
	input	wire		i_wbu_uart_rx;
	output	wire		o_wbu_uart_tx;
	// input wire		i_wbu_uart_rts_n; // FT*'s perspective
	output wire		o_wbu_uart_cts_n;
	input	wire		i_hdmirx_clk_p, i_hdmirx_clk_n;
	input	wire	[2:0]	i_hdmirx_p, i_hdmirx_n;
	output	wire		o_hdmitx_clk_p, o_hdmitx_clk_n;
	output	wire	[2:0]	o_hdmitx_p, o_hdmitx_n;
	// Quad SPI flash
	output	wire		o_flash_sck;
	output	wire		o_flash_cs_n;
	inout	wire	[3:0]	io_flash_dat;
	// GPIO wires
	input	wire		i_pi_reset_n, i_soft_reset, i_hdmitx_hpd_n;
	output	wire	[3:0]	o_tp;
	output	wire		o_si5324_rst, o_hdmirx_hpd_n;
	input	wire		i_si5324_int;
	// SDIO SD Card
	// {{{

	output	wire		o_sdcard_clk;


	input	wire		i_sdcard_cd_n;

	inout	wire		io_sdcard_cmd;
	inout	wire	[4-1:0]	io_sdcard_dat;
	// }}}
	// eMMC Card
	// {{{

	output	wire	o_emmc_clk;

	input	wire		i_emmc_ds;


	inout	wire		io_emmc_cmd;
	inout	wire	[8-1:0]	io_emmc_dat;
	// }}}
	input	wire		i_sdslav_clk;
	inout	wire		io_sdslav_cmd;
	inout	wire	[3:0]	io_sdslav_dat;
	// I/O declarations for the DDR3 SDRAM
	// {{{
	output	wire		o_ddr3_reset_n;
	output	wire	[1:0]	o_ddr3_cke;
	output	wire	[0:0]	o_ddr3_clk_p, o_ddr3_clk_n;
	output	wire	[1:0]	o_ddr3_s_n; // o_ddr3_s_n[1] is set to 0 since controller only support single rank
	output	wire	[0:0]	o_ddr3_ras_n, o_ddr3_cas_n, o_ddr3_we_n;
	output	wire	[DDR3_CONTROLLERBA_BITS-1:0]	o_ddr3_ba;
	output	wire	[15:0]	o_ddr3_a; //set to max of 16 bits, but only ROW_BITS bits are relevant
	output	wire	[1:0]	o_ddr3_odt;
	output	wire	[DDR3_CONTROLLERBYTE_LANES-1:0]	o_ddr3_dm;
	inout	wire	[(DDR3_CONTROLLERDQ_BITS*DDR3_CONTROLLERBYTE_LANES)/8-1:0]	io_ddr3_dqs_p, io_ddr3_dqs_n;
	inout	wire	[(DDR3_CONTROLLERDQ_BITS*DDR3_CONTROLLERBYTE_LANES)-1:0]	io_ddr3_dq;
	// }}}

	input	wire	i_sata_p, i_sata_n;
	output	wire	o_sata_p, o_sata_n;
	input	wire	i_clk_150mhz_p, i_clk_150mhz_n;


	//
	// Declaring component data, internal wires and registers
	//
	// These declarations just copy data from the @TOP.DEFNS key
	// within the component data files.
	//
	// FAN definitions
	// {{{
	wire	i_fan_sda, i_fan_scl,
		o_fan_sda, o_fan_scl;
	// }}}
	// I2CCPU definitions
	// {{{
	wire	i_i2c_sda, i_i2c_scl,
		o_i2c_sda, o_i2c_scl;
	reg		r_i2c_mxrst_n;
	reg	[2:0]	r_i2c_mxrst_dly;
	// }}}
	// CEC declarations.
	wire	i_hdmirx_cec, i_hdmitx_cec;
	wire	o_hdmirx_cec, o_hdmitx_cec;
	// 10Gb Ethernet
	wire	[4-1:0]		gnet_rx_clk, gnet_tx_clk;
	wire	[32*4-1:0]	gnet_rx_data;
	wire	[32*4-1:0]	gnet_tx_data;
	wire	[4-1:0]		gnet_phy_fault;
	wire	[4:0]		gnet_locked;
	wire	[8-1:0]	w_led;
	wire	[5-1:0]	w_btn;
	// I2CCPU definitions
	// {{{
	wire	i_edid_sda, i_edid_scl,
		o_edid_sda, o_edid_scl;
	// }}}
	// Definitions for the clock generation circuit
	wire		s_sirefclk_clk, w_sirefclk_ce;
			// w_sirefclk_pll_locked	-- not used at present
	wire		s_clk4x; // s_clk4x_unbuffered,
			// s_clksync, s_clksync_unbuffered;
	wire	[7:0]	w_sirefclk_word;
	wire		s_clk, s_reset, sysclk_locked, s_clk_nobuf,
			clk_feedback, clk_feedback_bufd,
			s_lcl_pixclk_nobuf, s_clk4x_unbuffered,
			s_clk300_nobuf, s_clk300, pre_mig_clk;
	reg	[2:0]	pipe_reset, pll_reset;
	reg	[6:0]	refdly_reset_ctr;
	wire		refdly_ready;
	// Verilator lint_off UNUSED
	wire		ign_cpu_stall, ign_cpu_ack;
	wire	[31:0]	ign_cpu_idata;
`ifdef	VERILATOR
	wire		ign_cpu_prof_stb;
	wire	[25+$clog2(512/8)-1:0] ign_cpu_prof_addr;
	wire [31:0]	ign_cpu_prof_ticks;
`endif
	// Verilator lint_on  UNUSED
	wire	s_siclk_unbuf, s_siclk;
	wire	s_clk200, s_clk200_unbuf;
	wire	[9:0]	hdmirx_red, hdmirx_grn, hdmirx_blu;
	wire	[9:0]	hdmitx_red, hdmitx_grn, hdmitx_blu;
	wire	[1:0]	w_pxclk_sel;
	wire		hdmirx_clk, hdmi_ck, hdmi_serdes_clk;
	wire		pxrx_locked, pix_reset_n;
	wire [15-1:0]	set_hdmi_delay, actual_hdmi_delay;
	wire		w_flash_sck, w_flash_cs_n;
	wire	[1:0]	flash_bmod;
	wire	[3:0]	i_flash_dat, o_flash_dat;
	// GPIO declarations.  The two wire busses are just virtual lists of
	// input (or output) ports.
	wire	[16-1:0]	i_gpio;
	wire	[8-1:0]	o_gpio;
	// SDIO SD Card definitions
	// {{{
	wire		w_sdio_hwreset_n, w_sdio_1p8v;
	wire		w_sdio_cfg_ddr;
	wire		w_sdio_cfg_ds, w_sdio_cfg_dscmd;
	wire	[4:0]	w_sdio_cfg_sample_shift;
	wire		w_sdio_expect_token;
	wire		w_sdio_cmd_tristate;
	wire		w_sdio_data_tristate;
		//
	wire	[7:0]	w_sdio_sdclk;
	wire		w_sdio_cmd_en;
	wire	[1:0]	w_sdio_cmd_data;
	wire		w_sdio_data_en;
	wire		w_sdio_rx_en;
	wire	[31:0]	w_sdio_tx_data;
		//
	wire	[1:0]	w_sdio_cmd_strb;
	wire	[1:0]	w_sdio_cmd_idata;
	wire		w_sdio_cmd_collision;
	wire		w_sdio_crcack,
			w_sdio_crcnak;
	wire		w_sdio_card_busy;
	wire	[1:0]	w_sdio_rx_strb;
	wire	[15:0]	w_sdio_rx_data;
		//
	wire		w_sdio_ac_valid;
	wire	[1:0]	w_sdio_ac_data;
	wire		w_sdio_ad_valid;
	wire	[31:0]	w_sdio_ad_data;

	wire		w_sdio_ck;
	wire		w_sdio_ds;
	wire	[31:0]	w_sdio_debug;
	// }}}

	// satadrp Definitions
	// {{{
	wire		sata_drp_cyc, sata_drp_stb, sata_drp_we,
			sata_drp_stall, sata_drp_ack;
	wire	[10:0]	sata_drp_addr;
	wire	[31:0]	sata_drp_data, sata_drp_idata;
	wire	[3:0]	sata_drp_sel;
	// }}}
	// eMMC Card definitions
	// {{{
	wire		w_emmc_hwreset_n, w_emmc_1p8v;
	wire		w_emmc_cfg_ddr;
	wire		w_emmc_cfg_ds, w_emmc_cfg_dscmd;
	wire	[4:0]	w_emmc_cfg_sample_shift;
	wire		w_emmc_expect_token;
	wire		w_emmc_cmd_tristate;
	wire		w_emmc_data_tristate;
		//
	wire	[7:0]	w_emmc_sdclk;
	wire		w_emmc_cmd_en;
	wire	[1:0]	w_emmc_cmd_data;
	wire		w_emmc_data_en;
	wire		w_emmc_rx_en;
	wire	[31:0]	w_emmc_tx_data;
		//
	wire	[1:0]	w_emmc_cmd_strb;
	wire	[1:0]	w_emmc_cmd_idata;
	wire		w_emmc_cmd_collision;
	wire		w_emmc_crcack,
			w_emmc_crcnak;
	wire		w_emmc_card_busy;
	wire	[1:0]	w_emmc_rx_strb;
	wire	[15:0]	w_emmc_rx_data;
		//
	wire		w_emmc_ac_valid;
	wire	[1:0]	w_emmc_ac_data;
	wire		w_emmc_ad_valid;
	wire	[31:0]	w_emmc_ad_data;

	wire		w_emmc_ck;
	wire		w_emmc_ds;
	wire	[31:0]	w_emmc_debug;
	// }}}

	wire	[3:0]	su_emmc_nc;	// Unused / noconnect wires
	wire	i_emmc_cd_n;

	assign	i_emmc_cd_n = 1'b0;
	// SDSLAVE/sdslav definitions
	// {{{
	wire		w_sdslav_clk;
	wire		w_sdslav_tx_cmd,
			w_sdslav_cmd_tristate;
	wire	[15:0]	w_sdslav_data;
	wire	[7:0]	w_sdslav_tx_data_tristate;
	wire	[1:0]	w_sdslav_tx_ds;

	wire		w_sdslav_rx_cmd,
			w_sdslav_rx_cmd_collision;
	wire	[15:0]	w_sdslav_rx_dat;

	wire		ign_sdslav_ds;
	// }}}
	// Wires connected to PHY interface of DDR3 controller
	// {{{
	genvar ddr3_controllergen_index;

	wire	[DDR3_CONTROLLERDQ_BITS*DDR3_CONTROLLERBYTE_LANES*8-1:0] ddr3_controller_iserdes_data;
	wire	[DDR3_CONTROLLERBYTE_LANES*8-1:0] ddr3_controller_iserdes_dqs,
				ddr3_controller_iserdes_bitslip_reference;
	wire    [DDR3_CONTROLLERCMD_LEN*DDR3_CONTROLLERSERDES_RATIO-1:0]
				ddr3_controller_cmd;
	wire    [DDR3_CONTROLLERDQ_BITS*DDR3_CONTROLLERBYTE_LANES*8-1:0]
				ddr3_controller_data;
	wire    [(DDR3_CONTROLLERDQ_BITS*DDR3_CONTROLLERBYTE_LANES*8)/8-1:0]
				ddr3_controller_dm;
	wire    [4:0]	ddr3_controller_odelay_data_cntvaluein,
			ddr3_controller_odelay_dqs_cntvaluein,
			ddr3_controller_idelay_data_cntvaluein,
			ddr3_controller_idelay_dqs_cntvaluein;
	wire    [DDR3_CONTROLLERBYTE_LANES-1:0]	ddr3_controller_odelay_data_ld,
			ddr3_controller_odelay_dqs_ld, ddr3_controller_idelay_data_ld,
			ddr3_controller_idelay_dqs_ld, ddr3_controller_bitslip,
			ddr3_controller_debug_read_dqs_p,
			ddr3_controller_debug_read_dqs_n;
	wire    ddr3_controller_idelayctrl_rdy,
		ddr3_controller_dqs_tri_control, ddr3_controller_dq_tri_control,
		ddr3_controller_toggle_dqs, ddr3_controller_write_leveling_calib,
		ddr3_controller_reset;
	wire	ddr3_controller_debug_clk_p, ddr3_controller_debug_clk_n;
	// }}}
	// sata Definitions
	// {{{
	wire	s_clk_150mhz;
	wire	sata_phy_ready, sata_phy_init_err,
		sata_phy_reset;
	//
	wire		sata_txphy_clk, sata_txphy_ready,
			sata_txphy_elecidle, sata_txphy_cominit,
			sata_txphy_comwake, sata_txphy_comfinish,
			sata_txphy_primitive;
	wire	[31:0]	sata_txphy_data;
	//
	wire		sata_rxphy_clk, sata_rxphy_primitive;
	wire	[31:0]	sata_rxphy_data;
	wire		sata_rxphy_error, sata_rxphy_syncd,
			sata_rxphy_elecidle, sata_rxphy_cominit,
			sata_rxphy_comwake, sata_rxphy_cdrhold;
	wire		sata_phy_refclk;
	wire	[31:0]	sata_phy_debug;
	// Verilator lint_off UNUSED
	wire		ign_sata_stall, ign_sata_ack;
	wire	[31:0]	ign_sata_data;
	// Verilator lint_on  UNUSED
	// }}}


	//
	// Time to call the main module within main.v.  Remember, the purpose
	// of the main.v module is to contain all of our portable logic.
	// Things that are Xilinx (or even Altera) specific, or for that
	// matter anything that requires something other than on-off logic,
	// such as the high impedence states required by many wires, is
	// kept in this (toplevel.v) module.  Everything else goes in
	// main.v.
	//
	// We automatically place s_clk, and s_reset here.  You may need
	// to define those above.  (You did, didn't you?)  Other
	// component descriptions come from the keys @TOP.MAIN (if it
	// exists), or @MAIN.PORTLIST if it does not.
	//

	main	thedesign(s_clk, s_reset,
		// sirefclk
		s_sirefclk_clk,
		// FAN/fan
		i_fan_sda, i_fan_scl,
		o_fan_sda, o_fan_scl,
		o_fan_pwm, o_fan_sys, i_fan_tach,
		// I2CCPU
		i_i2c_sda, i_i2c_scl,
		o_i2c_sda, o_i2c_scl,
		// CEC wires
		i_hdmirx_cec, o_hdmirx_cec,
		i_hdmitx_cec, o_hdmitx_cec,
		gnet_rx_clk, gnet_rx_data,
		gnet_tx_clk, gnet_tx_data,
		gnet_phy_fault, o_gnet_linkup, o_gnet_activity,
		i_gnet_los, gnet_locked,
		i_sw, w_btn, w_led,
		// I2CCPU
		i_edid_sda, i_edid_scl,
		o_edid_sda, o_edid_scl,
		// Clock Generator ports
		w_sirefclk_word, w_sirefclk_ce,
		// (Unused) ZipCPU Simulation port
		1'b0, 1'b0, 1'b0, 7'h0, 32'h0,
		ign_cpu_stall, ign_cpu_ack, ign_cpu_idata,
`ifdef	VERILATOR
		ign_cpu_prof_stb, ign_cpu_prof_addr, ign_cpu_prof_ticks,
`endif
		// ZipCPU reset port
		s_reset,
		s_siclk,
		s_clk200,
		// UART/host to wishbone interface
		i_wbu_uart_rx, o_wbu_uart_tx,
		o_wbu_uart_cts_n,
		// HDMI control ports
		hdmirx_clk, hdmi_ck,	// Depending on s_siclk
		hdmirx_red, hdmirx_grn, hdmirx_blu,
		hdmitx_red, hdmitx_grn, hdmitx_blu,
		set_hdmi_delay, actual_hdmi_delay,
		pix_reset_n, pxrx_locked,
		w_pxclk_sel,
		// Quad SPI flash
		w_flash_cs_n, w_flash_sck, o_flash_dat, i_flash_dat, flash_bmod,
		// GPIO wires
		i_gpio, o_gpio,
		// SDIO SD Card
		!i_sdcard_cd_n,
		//
		w_sdio_cfg_ddr,
		w_sdio_cfg_ds,
		w_sdio_cfg_dscmd,
		w_sdio_cfg_sample_shift,
		w_sdio_expect_token,
		w_sdio_cmd_tristate,
		w_sdio_data_tristate,
		//
		w_sdio_sdclk,
		w_sdio_cmd_en,
		w_sdio_cmd_data,
		w_sdio_data_en,
		w_sdio_rx_en,
		w_sdio_tx_data,
		//
		w_sdio_cmd_strb,
		w_sdio_cmd_idata,
		w_sdio_cmd_collision,
		w_sdio_crcack,
		w_sdio_crcnak,
		w_sdio_card_busy,
		w_sdio_rx_strb,
		w_sdio_rx_data,
		//
		w_sdio_ac_valid,
		w_sdio_ac_data,
		w_sdio_ad_valid,
		w_sdio_ad_data,
		w_sdio_hwreset_n, w_sdio_1p8v, 1'b0,
		w_sdio_debug,
		sata_drp_cyc, sata_drp_stb, sata_drp_we, sata_drp_addr,
		sata_drp_data, sata_drp_sel, sata_drp_stall, sata_drp_ack,
		sata_drp_idata,
		// eMMC Card
		!i_emmc_cd_n,
		//
		w_emmc_cfg_ddr,
		w_emmc_cfg_ds,
		w_emmc_cfg_dscmd,
		w_emmc_cfg_sample_shift,
		w_emmc_expect_token,
		w_emmc_cmd_tristate,
		w_emmc_data_tristate,
		//
		w_emmc_sdclk,
		w_emmc_cmd_en,
		w_emmc_cmd_data,
		w_emmc_data_en,
		w_emmc_rx_en,
		w_emmc_tx_data,
		//
		w_emmc_cmd_strb,
		w_emmc_cmd_idata,
		w_emmc_cmd_collision,
		w_emmc_crcack,
		w_emmc_crcnak,
		w_emmc_card_busy,
		w_emmc_rx_strb,
		w_emmc_rx_data,
		//
		w_emmc_ac_valid,
		w_emmc_ac_data,
		w_emmc_ad_valid,
		w_emmc_ad_data,
		w_emmc_hwreset_n, w_emmc_1p8v, 1'b0,
		w_emmc_debug,
		// SDSLAVE
		w_sdslav_clk,
		w_sdslav_tx_cmd,
		w_sdslav_cmd_tristate,
		w_sdslav_data,
		w_sdslav_tx_data_tristate,
		w_sdslav_tx_ds,

		w_sdslav_rx_cmd,
		w_sdslav_rx_cmd_collision,
		w_sdslav_rx_dat,
	// DDR3 Controller-PHY Interface
	ddr3_controller_iserdes_data, ddr3_controller_iserdes_dqs,
	ddr3_controller_iserdes_bitslip_reference,
	ddr3_controller_idelayctrl_rdy,
	ddr3_controller_cmd,
	ddr3_controller_dqs_tri_control, ddr3_controller_dq_tri_control,
	ddr3_controller_toggle_dqs, ddr3_controller_data, ddr3_controller_dm,
	ddr3_controller_odelay_data_cntvaluein, ddr3_controller_odelay_dqs_cntvaluein,
	ddr3_controller_idelay_data_cntvaluein, ddr3_controller_idelay_dqs_cntvaluein,
	ddr3_controller_odelay_data_ld, ddr3_controller_odelay_dqs_ld,
	ddr3_controller_idelay_data_ld, ddr3_controller_idelay_dqs_ld,
	ddr3_controller_bitslip,
	ddr3_controller_write_leveling_calib,
	ddr3_controller_reset,
		sata_phy_ready, sata_phy_init_err,
		sata_phy_reset,
		//
		sata_txphy_clk, sata_txphy_ready,
			sata_txphy_elecidle, sata_txphy_cominit,
			sata_txphy_comwake, sata_txphy_comfinish,
			sata_txphy_primitive,
		sata_txphy_data,
		//
		sata_rxphy_clk, sata_rxphy_primitive,
		sata_rxphy_data,
		sata_rxphy_error, sata_rxphy_syncd,
			sata_rxphy_elecidle, sata_rxphy_cominit,
			sata_rxphy_comwake, sata_rxphy_cdrhold,
		sata_phy_refclk, sata_phy_debug);


	//
	// Our final section to the toplevel is used to provide all of
	// that special logic that couldnt fit in main.  This logic is
	// given by the @TOP.INSERT tag in our data files.
	//


	////////////////////////////////////////////////////////////////////////
	//
	// FAN IO buffers
	// {{{

	// We need these in order to (properly) ensure the high impedance
	// states (pull ups) of the I2C I/O lines.  Our goals are:
	//
	//	o_fan_X	io_fan_X		Derived:T
	//	1'b0		1'b0			1'b0
	//	1'b1		1'bz			1'b1
	//
	IOBUF fansclp(
		// {{{
		.I(1'b0),
		.T(o_fan_scl),
		.O(i_fan_scl),
		.IO(io_temp_scl)
		// }}}
	);

	IOBUF fansdap(
		// {{{
		.I(1'b0),
		.T(o_fan_sda),
		.O(i_fan_sda),
		.IO(io_temp_sda)
		// }}}
	);
	// }}}

	////////////////////////////////////////////////////////////////////////
	//
	// I2C IO buffers
	// {{{

	// We need these in order to (properly) ensure the high impedance
	// states (pull ups) of the I2C I/O lines.  Our goals are:
	//
	//	o_i2c_X	io_i2c_X		Derived:T
	//	1'b0		1'b0			1'b0
	//	1'b1		1'bz			1'b1
	//
	IOBUF i2csclp(
		// {{{
		.I(1'b0),
		.T(o_i2c_scl),
		.O(i_i2c_scl),
		.IO(io_i2c_scl)
		// }}}
	);

	IOBUF i2csdap(
		// {{{
		.I(1'b0),
		.T(o_i2c_sda),
		.O(i_i2c_sda),
		.IO(io_i2c_sda)
		// }}}
	);

	initial	{ r_i2c_mxrst_n, r_i2c_mxrst_dly } = 0;
	always @(posedge s_clk or negedge sysclk_locked)
	if (!sysclk_locked)
		{ r_i2c_mxrst_n, r_i2c_mxrst_dly } <= 0;
	else
		{ r_i2c_mxrst_n, r_i2c_mxrst_dly } <= { r_i2c_mxrst_dly, 1'b1 };

	assign	o_i2c_mxrst_n = r_i2c_mxrst_n;
	// }}}

	// CEC logic
	IOBUF hdmirx_cec (.T(o_hdmirx_cec), .I(1'b0), .O(i_hdmirx_cec), .IO(io_hdmirx_cec));
	IOBUF hdmitx_cec (.T(o_hdmitx_cec), .I(1'b0), .O(i_hdmitx_cec), .IO(io_hdmitx_cec));

	assign	o_gnettx_disable = -1;

	xgtxphy #(
		.NDEV(4)
	) u_gnet_gtx_phy (
		// {{{
		.i_wb_clk(s_clk),
		.o_phy_fault(gnet_phy_fault),
		.o_lock_status(gnet_locked),
		//
		.S_CLK(  gnet_tx_clk),
		.S_DATA( gnet_tx_data),
		//
		.M_CLK(  gnet_rx_clk),
		.M_DATA( gnet_rx_data),
		//
		.i_refck_p(i_clk_156mhz_p), .i_refck_n(i_clk_156mhz_n),
		.i_rx_p(i_gnet_p), .i_rx_n(i_gnet_n),
		.o_tx_p(o_gnet_p), .o_tx_n(o_gnet_n)
		// }}}
	);

	////////////////////////////////////////////////////////////////////////
	//
	// SPIO (Button/LED/switch) logic
	// {{{
	assign	o_led = { w_led[8-1:2], (w_led[1] || !sysclk_locked),
			w_led[0] | s_reset };

	assign	w_btn = ~{ i_nbtn_u, i_nbtn_l, i_nbtn_c, i_nbtn_r, i_nbtn_d };
	// }}}

	////////////////////////////////////////////////////////////////////////
	//
	// EDID I2C IO buffers
	// {{{

	// We need these in order to (properly) ensure the high impedance
	// states (pull ups) of the I2C I/O lines.  Our goals are:
	//
	//	o_edid_X	io_edid_X		Derived:T
	//	1'b0		1'b0			1'b0
	//	1'b1		1'bz			1'b1
	//
	IOBUF edidsclp(
		// {{{
		.I(1'b0),
		.T(o_edid_scl),
		.O(i_edid_scl),
		.IO(io_hdmirx_scl)
		// }}}
	);

	IOBUF edidsdap(
		// {{{
		.I(1'b0),
		.T(o_edid_sda),
		.O(i_edid_sda),
		.IO(io_hdmirx_sda)
		// }}}
	);

	// }}}

	////////////////////////////////////////////////////////////////////////
	//
	// Clock generator for the Si5324
	// {{{
/*
	PLLE2_BASE #(
		// {{{
		.CLKFBOUT_MULT(8),
		.CLKFBOUT_PHASE(0.0),
		.CLKIN1_PERIOD(10),
		.CLKOUT0_DIVIDE(4),
		.CLKOUT1_DIVIDE(2)
		// }}}
	) gen_sysclk(
		// {{{
		.CLKIN1(i_clk),
		.CLKOUT0(s_clk_200mhz_unbuffered),
		.CLKOUT1(s_clk4x_unbuffered),
		.PWRDWN(1'b0), .RST(1'b0),
		.CLKFBOUT(sysclk_feedback),
		.CLKFBIN(sysclk_feedback),
		.LOCKED(sysclk_locked)
		// }}}
	);
*/
	// BUFG	clksync_buf(.I(s_clksync_unbuffered), .O(s_clk));
	BUFG	clk4x_buf(.I(s_clk4x_unbuffered), .O(s_clk4x));

	xgenclk #(
		.OPT_LCLCLOCK(1'b1)
	) u_xsirefclk(
		// {{{
		.i_clk(s_clk), .i_hsclk(s_clk4x),
		.i_ce(w_sirefclk_ce),
		.i_word(w_sirefclk_word),
		.o_pin({ io_siref_clk_p, io_siref_clk_n }),
		.o_clk(s_sirefclk_clk)
		// }}}
	);
	// }}}

	////////////////////////////////////////////////////////////////////////
	//
	// Default clock setup
	// {{{
	// assign	s_clk=s_clk200;
	// assign	sysclk_locked = 1'b1;

	initial	pll_reset = -1;
	always @(posedge s_clk200)
		pll_reset <= { pll_reset[1:0], 1'b0 };

	initial	pipe_reset = -1;
	always @(posedge s_clk or negedge sysclk_locked)
	if (!sysclk_locked)
		pipe_reset <= -1;
	else
		pipe_reset <= { pipe_reset[1:0], 1'b0 };

	assign	s_reset = pipe_reset[2];

	PLLE2_BASE #(
		.CLKFBOUT_MULT(6),		// 200MHz*6 => 1200MHz
		.CLKFBOUT_PHASE(0.0),
		.CLKIN1_PERIOD(5),
		.CLKOUT0_DIVIDE(12),		// Divide by 2x
		.CLKOUT1_DIVIDE(3),		// Multiply by 2x
		.CLKOUT2_DIVIDE(14),		// Multiply by 6/14
		.CLKOUT3_DIVIDE(4)		// Multiply by 3/2
	) u_syspll (
		.RST(pll_reset[2]),
		.CLKOUT0(s_clk_nobuf),		// 100MHz
		.CLKOUT1(s_clk4x_unbuffered),	// 400MHz
		.CLKOUT2(s_lcl_pixclk_nobuf),	//  85.7MHz
		.CLKOUT3(s_clk300_nobuf),	// 300MHz
		//
		.CLKFBOUT(clk_feedback),
		.LOCKED(sysclk_locked),
		.CLKIN1(s_clk200),	// 200MHz
		.PWRDWN(1'b0),
		.CLKFBIN(clk_feedback_bufd)
	);

	BUFG	feedback_buffer(.I(clk_feedback), .O(clk_feedback_bufd));
	BUFG	sysclk_buffer(.I(s_clk_nobuf), .O(pre_mig_clk));
	BUFG	clk300_buf(.I(s_clk300_nobuf), .O(s_clk300));
	// BUFG	sysclk_buffer(.I(s_lcl_pixclk_nobuf), .O(s_lcl_pixclk));

	// IDELAYCTRL
	// {{{
	// Min reset width of 52ns, or 9 clocks at 150MHz
	always @(posedge s_clk300 or negedge sysclk_locked)
	if (!sysclk_locked)
		refdly_reset_ctr <= 0;
	else if (!refdly_reset_ctr[5])
		refdly_reset_ctr <= refdly_reset_ctr + 1;

	(* IODELAY_GROUP="HDMI-DLYGROUP" *)
	IDELAYCTRL
	u_dlyctrl (.REFCLK(s_clk300), .RST(refdly_reset_ctr[5]),
		.RDY(refdly_ready));
	// }}}
	// }}}

	IBUFDS_GTE2
	u_siclk_buf(
		.I(i_clk_si_p), .IB(i_clk_si_n),
		.CEB(1'b0),
		.O(s_siclk_unbuf)
	);

	BUFG
	u_siclk_bufg (
		.I(s_siclk_unbuf),
		.O(s_siclk)
	);

	////////////////////////////////////////////////////////////////////////
	//
	// 200MHz clock ingestion
	// {{{
	IBUFDS
	ibuf_ck200 (
		.I(i_clk_200mhz_p), .IB(i_clk_200mhz_n),
		.O(s_clk200_unbuf)
	);

	BUFG
	ck200_buf(.I(s_clk200_unbuf), .O(s_clk200));
	// }}}

	////////////////////////////////////////////////////////////////////////
	//
	// HDMI
	// {{{

	// Start with clock generation and propagation
	// {{{
	xpxclk
	u_xpxclk (
		.i_sysclk(s_clk),		// System clock
		.i_cksel(w_pxclk_sel),		// Clock select switch
		//
		.i_hdmirx_clk_p(i_hdmirx_clk_p),	// HDMI RX input clock
		.i_hdmirx_clk_n(i_hdmirx_clk_n),
		.i_lcl_pixclk(s_lcl_pixclk_nobuf),	// Locally generated clk
		.i_siclk(s_siclk),			// Si5324 clock
		//
		.o_hdmick_locked(pxrx_locked),
		.o_hdmirx_clk(hdmirx_clk),	// Clk for measurement only
		.o_pixclk(hdmi_ck),		// Pixel clock
		.o_hdmick(hdmi_serdes_clk)	// HS pixel clock
	);
	// }}}

	// Ingest the HDMI data lines
	// {{{
	xhdmiin
	u_hdmirx_red(
		.i_clk(hdmi_ck), .i_hsclk(hdmi_serdes_clk),
		.i_reset_n(pix_reset_n),
		.i_delay(set_hdmi_delay[14:10]),
		.o_delay(actual_hdmi_delay[14:10]),
		.i_hs_wire({ i_hdmirx_p[2], i_hdmirx_n[2] }),
		.o_word(hdmirx_red)
	);

	xhdmiin
	u_hdmirx_grn(
		.i_clk(hdmi_ck), .i_hsclk(hdmi_serdes_clk),
		.i_reset_n(pix_reset_n),
		.i_delay(set_hdmi_delay[9:5]),
		.o_delay(actual_hdmi_delay[9:5]),
		.i_hs_wire({ i_hdmirx_p[1], i_hdmirx_n[1] }),
		.o_word(hdmirx_grn)
	);

	xhdmiin
	u_hdmirx_blu(
		.i_clk(hdmi_ck), .i_hsclk(hdmi_serdes_clk),
		.i_reset_n(pix_reset_n),
		.i_delay(set_hdmi_delay[4:0]),
		.o_delay(actual_hdmi_delay[4:0]),
		.i_hs_wire({ i_hdmirx_p[0], i_hdmirx_n[0] }),
		.o_word(hdmirx_blu)
	);
	// }}}

	// Output the HDMI TX data lines
	// {{{
	xhdmiout
	u_hdmitx_clk(
		.i_clk(hdmi_ck), .i_hsclk(hdmi_serdes_clk),
		.i_reset_n(pix_reset_n),
		.i_word(10'b11111_00000),
		.o_port({ o_hdmitx_clk_p, o_hdmitx_clk_n })
	);

	xhdmiout
	u_hdmitx_red(
		.i_clk(hdmi_ck), .i_hsclk(hdmi_serdes_clk),
		.i_reset_n(pix_reset_n),
		.i_word(hdmitx_red),
		.o_port({ o_hdmitx_p[2], o_hdmitx_n[2] })
	);

	xhdmiout
	u_hdmitx_grn(
		.i_clk(hdmi_ck), .i_hsclk(hdmi_serdes_clk),
		.i_reset_n(pix_reset_n),
		.i_word(hdmitx_grn),
		.o_port({ o_hdmitx_p[1], o_hdmitx_n[1] })
	);

	xhdmiout
	u_hdmitx_blu(
		.i_clk(hdmi_ck), .i_hsclk(hdmi_serdes_clk),
		.i_reset_n(pix_reset_n),
		.i_word(hdmitx_blu),
		.o_port({ o_hdmitx_p[0], o_hdmitx_n[0] })
	);
	// }}}

	// }}}

	////////////////////////////////////////////////////////////////////////
	//
	// QSPI Flash IO pin handling
	// {{{
	//
	// Wires for setting up the QSPI flash wishbone peripheral
	//
	//
	// QSPI)BMOD, Quad SPI bus mode, Bus modes are:
	//	0?	Normal serial mode, one bit in one bit out
	//	10	Quad SPI mode, going out
	//	11	Quad SPI mode coming from the device (read mode)
	xqflex #(
		.OPT_CLOCK(1'b1), .OPT_PHASE(1'b1)
	) u_xqflex (
		// {{{
		.i_clk(s_clk), .i_cs_n(w_flash_cs_n),
		.i_sck({ (1==0) ? 1'b0 : w_flash_sck,
			w_flash_sck }),
		.i_dat(o_flash_dat), .o_dat(i_flash_dat), .i_bmod(flash_bmod),
		.o_cs_n(o_flash_cs_n), .o_sck(o_flash_sck), .io_dat(io_flash_dat)
	);

	// }}}

	////////////////////////////////////////////////////////////////////////
	//
	// GPIO adjustments
	// {{{
	// Set to '1' when there's something to say.  Hence, the reset
	//	inputs will be '1' when the reset is active, the HDMI detect
	//	will be '1' when an HDMI is detected, the PLL lock signals
	//	will be '1' when not locked, etc.
	assign	i_gpio = { 10'h0,
`ifdef	VIDPIPE_ACCESS
		!pxrx_locked,
`else
		1'b1,
`endif
		!i_hdmitx_hpd_n,
		i_si5324_int,!sysclk_locked,!i_pi_reset_n,i_soft_reset };
	assign	o_tp = o_gpio[3:0];
	assign	o_si5324_rst = o_gpio[4];
	assign	o_hdmirx_hpd_n = !o_gpio[5];
	// o_trace = o_gpio[6]; // But this is for simulation only, so ignore
	// o_error = o_gpio[7]; // SIM ONLY: Internal error detection
	// }}}

`ifdef	VERILATOR
	wire		v_sdio_cmd_tristate,
			v_o_sdio_cmd,
			v_i_sdio_cmd;
	wire	[4-1:0]	v_sdio_dat_tristate,
			v_o_sdio_dat,
			v_i_sdio_dat;
`endif

	sdfrontend #(
		.OPT_SERDES(1'b1),
		.OPT_DDR(1'b1),
		.NUMIO(4),
		.BUSY_CLOCKS(16),
		.OPT_CRCTOKEN(1)
	) u_sdio_frontend (
		// {{{
		.i_clk(s_clk), .i_hsclk(s_clk4x), .i_reset(s_reset),
		// Configuration
		.i_cfg_ddr(w_sdio_cfg_ddr),
		.i_cfg_ds(w_sdio_cfg_ds),
		.i_cfg_dscmd(w_sdio_cfg_dscmd),
		.i_sample_shift(w_sdio_cfg_sample_shift),
		.i_expect_token(w_sdio_expect_token),
		.i_cmd_tristate(w_sdio_cmd_tristate),
		.i_data_tristate(w_sdio_data_tristate),
		// Run-time inputs
		.i_sdclk(w_sdio_sdclk),
		.i_cmd_en(w_sdio_cmd_en),
		.i_cmd_data(w_sdio_cmd_data),
		.i_data_en(w_sdio_data_en),
		.i_rx_en(w_sdio_rx_en),
		.i_tx_data(w_sdio_tx_data),
		// Return values
		.o_cmd_strb(w_sdio_cmd_strb),
		.o_cmd_data(w_sdio_cmd_idata),
		.o_cmd_collision(w_sdio_cmd_collision),
		.o_crcack(w_sdio_crcack),
		.o_crcnak(w_sdio_crcnak),
		.o_data_busy(w_sdio_card_busy),
		.o_rx_strb( w_sdio_rx_strb),
		.o_rx_data( w_sdio_rx_data),
		//
		.MAC_VALID(w_sdio_ac_valid),
		.MAC_DATA( w_sdio_ac_data),
		.MAD_VALID(w_sdio_ad_valid),
		.MAD_DATA( w_sdio_ad_data),
		// IO ports
		.o_ck(w_sdio_ck),
		.i_ds(w_sdio_ds),
`ifdef	VERILATOR
		.io_cmd_tristate(v_sdio_cmd_tristate),
		.o_cmd(v_o_sdio_cmd),
		.i_cmd(v_i_sdio_cmd),

		.io_dat_tristate(v_sdio_dat_tristate),
		.o_dat(v_o_sdio_dat),
		.i_dat(v_i_sdio_dat),
`else
		.io_cmd(io_sdcard_cmd),
		.io_dat(io_sdcard_dat),
`endif
		.o_debug(w_sdio_debug)
		// }}}
	);

`ifdef	VERILATOR
	genvar gv_sdio;

	assign	io_sdcard_cmd = v_sdio_cmd_tristate
			? 1'bz : v_o_sdio_cmd;

	generate for (gv_sdio=0; gv_sdio < 4;
			gv_sdio = gv_sdio+1)
	begin : GEN_SDIO_IO
		assign	io_sdcard_dat[gv_sdio]
				= v_sdio_dat_tristate[gv_sdio]
				? 1'bz : v_o_sdio_cmd;

		assign	v_i_sdio_dat[gv_sdio]
				= io_sdcard_dat[gv_sdio];
	end endgenerate
`endif


	assign	o_sdcard_clk = w_sdio_ck;

	assign	w_sdio_ds    = 1'b0;


`ifdef	VERILATOR
	wire		v_emmc_cmd_tristate,
			v_o_emmc_cmd,
			v_i_emmc_cmd;
	wire	[8-1:0]	v_emmc_dat_tristate,
			v_o_emmc_dat,
			v_i_emmc_dat;
`endif

	sdfrontend #(
		.OPT_SERDES(1'b1),
		.OPT_DDR(1'b0),
		.NUMIO(8),
		.BUSY_CLOCKS(16),
		.OPT_CRCTOKEN(1)
	) u_emmc_frontend (
		// {{{
		.i_clk(s_clk), .i_hsclk(s_clk4x), .i_reset(s_reset),
		// Configuration
		.i_cfg_ddr(w_emmc_cfg_ddr),
		.i_cfg_ds(w_emmc_cfg_ds),
		.i_cfg_dscmd(w_emmc_cfg_dscmd),
		.i_sample_shift(w_emmc_cfg_sample_shift),
		.i_expect_token(w_emmc_expect_token),
		.i_cmd_tristate(w_emmc_cmd_tristate),
		.i_data_tristate(w_emmc_data_tristate),
		// Run-time inputs
		.i_sdclk(w_emmc_sdclk),
		.i_cmd_en(w_emmc_cmd_en),
		.i_cmd_data(w_emmc_cmd_data),
		.i_data_en(w_emmc_data_en),
		.i_rx_en(w_emmc_rx_en),
		.i_tx_data(w_emmc_tx_data),
		// Return values
		.o_cmd_strb(w_emmc_cmd_strb),
		.o_cmd_data(w_emmc_cmd_idata),
		.o_cmd_collision(w_emmc_cmd_collision),
		.o_crcack(w_emmc_crcack),
		.o_crcnak(w_emmc_crcnak),
		.o_data_busy(w_emmc_card_busy),
		.o_rx_strb( w_emmc_rx_strb),
		.o_rx_data( w_emmc_rx_data),
		//
		.MAC_VALID(w_emmc_ac_valid),
		.MAC_DATA( w_emmc_ac_data),
		.MAD_VALID(w_emmc_ad_valid),
		.MAD_DATA( w_emmc_ad_data),
		// IO ports
		.o_ck(w_emmc_ck),
		.i_ds(w_emmc_ds),
`ifdef	VERILATOR
		.io_cmd_tristate(v_emmc_cmd_tristate),
		.o_cmd(v_o_emmc_cmd),
		.i_cmd(v_i_emmc_cmd),

		.io_dat_tristate(v_emmc_dat_tristate),
		.o_dat(v_o_emmc_dat),
		.i_dat(v_i_emmc_dat),
`else
		.io_cmd(io_emmc_cmd),
		.io_dat(io_emmc_dat),
`endif
		.o_debug(w_emmc_debug)
		// }}}
	);

`ifdef	VERILATOR
	genvar gv_emmc;

	assign	io_emmc_cmd = v_emmc_cmd_tristate
			? 1'bz : v_o_emmc_cmd;

	generate for (gv_emmc=0; gv_emmc < 8;
			gv_emmc = gv_emmc+1)
	begin : GEN_EMMC_IO
		assign	io_emmc_dat[gv_emmc]
				= v_emmc_dat_tristate[gv_emmc]
				? 1'bz : v_o_emmc_cmd;

		assign	v_i_emmc_dat[gv_emmc]
				= io_emmc_dat[gv_emmc];
	end endgenerate
`endif


	assign	o_emmc_clk = w_emmc_ck;

	assign	w_emmc_ds = i_emmc_ds;


	////////////////////////////////////////////////////////////////////////
	//
	// SDSLAVE front end
	// {{{

	BUFG u_sdslavck (
		.I(i_sdslav_clk),
		.O(w_sdslav_clk)
	);

	sdsfrontend #(
		.OPT_DS(1'b0), .NUMIO(4)
	) u_sdslav (
		// {{{
		.i_tx_cmd(w_sdslav_tx_cmd),
		.i_tx_cmd_tristate(w_sdslav_cmd_tristate),
		//
		.i_tx_data(w_sdslav_data),
		.i_tx_data_tristate(w_sdslav_tx_data_tristate),
		.i_tx_ds(w_sdslav_tx_ds),
		//
		.o_rx_cmd(w_sdslav_rx_cmd),
		.o_cmd_collision(w_sdslav_rx_cmd_collision),
		.o_rx_dat(w_sdslav_rx_dat),
		//
		.i_ck(w_sdslav_clk),
		.o_ds(ign_sdslav_ds),
		.io_cmd(io_sdslav_cmd),
		.io_dat(io_sdslav_dat)
		// }}}
	);

	// }}}

	////////////////////////////////////////////////////////////////////////
	//
	// DDR3 PHY logic
	// {{{
	assign	s_clk = pre_mig_clk;

	// DDR3 PHY Instantiation
	ddr3_phy #(
		// {{{
		.ROW_BITS(DDR3_CONTROLLERROW_BITS),	//width of row address
		.BA_BITS(DDR3_CONTROLLERBA_BITS),	//width of bank address
		.DQ_BITS(DDR3_CONTROLLERDQ_BITS),	//width of DQ
		.LANES(DDR3_CONTROLLERBYTE_LANES), //8 lanes of DQ
		.CONTROLLER_CLK_PERIOD(DDR3_CONTROLLERCONTROLLER_CLK_PERIOD), //ns, period of clock input to this DDR3 controller module
		.DDR3_CLK_PERIOD(DDR3_CLK_PERIOD), //ns, period of clock input to DDR3 RAM device
		.ODELAY_SUPPORTED(1)
		// }}}
	) ddr3_phy_inst (
		// {{{
		// clock and reset
		.i_controller_clk(s_clk),
		.i_ddr3_clk(s_clk4x),
		.i_ref_clk(s_clk200),
		.i_ddr3_clk_90(0), //required only when ODELAY_SUPPORTED is zero
		.i_rst_n(!s_reset),
		// Controller Interface
		.i_controller_reset(ddr3_controller_reset),
		.i_controller_cmd(ddr3_controller_cmd),
		.i_controller_dqs_tri_control(ddr3_controller_dqs_tri_control),
		.i_controller_dq_tri_control(ddr3_controller_dq_tri_control),
		.i_controller_toggle_dqs(ddr3_controller_toggle_dqs),
		.i_controller_data(ddr3_controller_data),
		.i_controller_dm(ddr3_controller_dm),
		.i_controller_odelay_data_cntvaluein(ddr3_controller_odelay_data_cntvaluein),
		.i_controller_odelay_dqs_cntvaluein(ddr3_controller_odelay_dqs_cntvaluein),
		.i_controller_idelay_data_cntvaluein(ddr3_controller_idelay_data_cntvaluein),
		.i_controller_idelay_dqs_cntvaluein(ddr3_controller_idelay_dqs_cntvaluein),
		.i_controller_odelay_data_ld(ddr3_controller_odelay_data_ld),
		.i_controller_odelay_dqs_ld(ddr3_controller_odelay_dqs_ld),
		.i_controller_idelay_data_ld(ddr3_controller_idelay_data_ld),
		.i_controller_idelay_dqs_ld(ddr3_controller_idelay_dqs_ld),
		.i_controller_bitslip(ddr3_controller_bitslip),
		.i_controller_write_leveling_calib(ddr3_controller_write_leveling_calib),
		.o_controller_iserdes_data(ddr3_controller_iserdes_data),
		.o_controller_iserdes_dqs(ddr3_controller_iserdes_dqs),
		.o_controller_iserdes_bitslip_reference(ddr3_controller_iserdes_bitslip_reference),
		.o_controller_idelayctrl_rdy(ddr3_controller_idelayctrl_rdy),
		// DDR3 I/O Interface
		.o_ddr3_clk_p(o_ddr3_clk_p),
		.o_ddr3_clk_n(o_ddr3_clk_n),
		.o_ddr3_reset_n(o_ddr3_reset_n),
		.o_ddr3_cke(o_ddr3_cke[0]), // CKE
		.o_ddr3_cs_n(o_ddr3_s_n[0]), // chip select signal (controls rank 1 only)
		.o_ddr3_ras_n(o_ddr3_ras_n), // RAS#
		.o_ddr3_cas_n(o_ddr3_cas_n), // CAS#
		.o_ddr3_we_n(o_ddr3_we_n), // WE#
		.o_ddr3_addr(o_ddr3_a[DDR3_CONTROLLERROW_BITS-1:0]),
		.o_ddr3_ba_addr(o_ddr3_ba),
		.io_ddr3_dq(io_ddr3_dq),
		.io_ddr3_dqs(io_ddr3_dqs_p),
		.io_ddr3_dqs_n(io_ddr3_dqs_n),
		.o_ddr3_dm(o_ddr3_dm),
		.o_ddr3_odt(o_ddr3_odt[0]), // on-die termination
		// DEBUG PHY
		.o_ddr3_debug_read_dqs_p(ddr3_controller_debug_read_dqs_p),
		.o_ddr3_debug_read_dqs_n(ddr3_controller_debug_read_dqs_n)
		// }}}
	);

        assign o_ddr3_s_n[1] = 1; // set to 1 (disabled) since controller only supports single rank
        assign o_ddr3_cke[1] = 0; // set to 0 (disabled) since controller only supports single rank
        assign o_ddr3_odt[1] = 0; // set to 0 (disabled) since controller only supports single rank
	generate for(ddr3_controllergen_index = DDR3_CONTROLLERROW_BITS;
			ddr3_controllergen_index < 16;
			ddr3_controllergen_index = ddr3_controllergen_index + 1)
	begin : GEN_UNUSED_DDR3_CONTROLLER_ASSIGN
		assign o_ddr3_a[ddr3_controllergen_index] = 0;
	end endgenerate
	// }}}

	////////////////////////////////////////////////////////////////////////
	//
	// SATA logic
	// {{{
	IBUFDS_GTE2
	u_sata_buf (
		.I(i_clk_150mhz_p), .IB(i_clk_150mhz_n), .CEB(1'b0),
			.O(s_clk_150mhz)
	);

	sata_phy #(
		.REFCLK_FREQUENCY(150)
	) u_sata (
		.i_wb_clk(s_clk), .i_reset(s_reset), .i_ref_clk200(s_clk200),
		.i_ref_sata_clk(s_clk_150mhz),
		// .i_user_reset(	sata_phy_reset),
		.o_ready(	sata_phy_ready),
		.o_init_err(	sata_phy_init_err),
		// WB DRP control
		// {{{
		.i_wb_cyc(sata_drp_cyc), .i_wb_stb(sata_drp_stb),
			.i_wb_we(sata_drp_we), .i_wb_addr(sata_drp_addr),
			.i_wb_data(sata_drp_data), .i_wb_sel(sata_drp_sel),
		.o_wb_stall(sata_drp_stall),
			.o_wb_ack(sata_drp_ack), .o_wb_data(sata_drp_idata),
		// }}}
		// Transmitter control
		// {{{
		.o_tx_clk(	sata_txphy_clk),
		.o_tx_ready(	sata_txphy_ready),
		.i_tx_elecidle(	sata_txphy_elecidle),
		.i_tx_cominit(	sata_txphy_cominit),
		.i_tx_comwake(	sata_txphy_comwake),
		.o_tx_comfinish(sata_txphy_comfinish),
		.i_tx_primitive(sata_txphy_primitive),
		.i_tx_data(	sata_txphy_data),
		// }}}
		// Receiver control
		// {{{
		.o_rx_clk(	sata_rxphy_clk),
		.o_rx_primitive(	sata_rxphy_primitive),
		.o_rx_data(	sata_rxphy_data),
		.o_rx_error(	sata_rxphy_error),
		.o_syncd(	sata_rxphy_syncd),
		//
		.o_rx_elecidle(	sata_rxphy_elecidle),
		.o_rx_cominit_detect(	sata_rxphy_cominit),
		.o_rx_comwake_detect(	sata_rxphy_comwake),
		.i_rx_cdrhold(	sata_rxphy_cdrhold),
		// }}}
		// Connections to external pads
		// {{{
		.o_tx_p(o_sata_p), .o_tx_n(o_sata_n),
		.i_rx_p(i_sata_p), .i_rx_n(i_sata_n),
		// }}}
		.o_refclk(sata_phy_refclk),
		.o_debug(sata_phy_debug)
	);
	// }}}



endmodule // end of toplevel.v module definition
