////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./regdefs.h
// {{{
// Project:	10Gb Ethernet switch
//
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga -I .: -d -o . allclocks.txt siclk.txt sirefclk.txt global.txt wbdown.txt icape.txt version.txt pwrcount.txt rtccount.txt gpio.txt spio.txt wbuconsole.txt zipmaster.txt bkram.txt ddr3.txt flash.txt sdio.txt emmc.txt sdslave.txt sata.txt netrouter.txt cpunet.txt netstats.txt busscope.txt routescope.txt i2cscope.txt gatescope.txt netscope.txt sdioscope.txt emmcscope.txt flashscope.txt satascope.txt mem_bkram_only.txt mem_sdram_only.txt mem_flash_bkram.txt mem_full.txt mem_bootrom_bkram.txt i2ccpu.txt fan.txt sirefclkcounter.txt netclk.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2023-2026, Gisselquist Technology, LLC
// {{{
// This file is part of the ETH10G project.
//
// The ETH10G project contains free software and gateware, licensed under the
// terms of the 3rd version of the GNU General Public License as published by
// the Free Software Foundation.
//
// This project is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
// }}}
// License:	GPL, v3, as defined and found on www.gnu.org,
// {{{
//		http://www.gnu.org/licenses/gpl.html
//
////////////////////////////////////////////////////////////////////////////////
//
// }}}
#ifndef	REGDEFS_H
#define	REGDEFS_H


//
// The @REGDEFS.H.INCLUDE tag
//
// @REGDEFS.H.INCLUDE for masters
// @REGDEFS.H.INCLUDE for peripherals
// And finally any master REGDEFS.H.INCLUDE tags
// End of definitions from REGDEFS.H.INCLUDE


//
// Register address definitions, from @REGS.#d
//
// FLASH erase/program configuration registers
#define	R_FLASHCFG        	0x02000000	// 02000000, wbregs names: FLASHCFG, QSPIC
// busscope compressed scope
#define	R_BUSSCOPE        	0x02000100	// 02000100, wbregs names: BUSSCOPE
#define	R_BUSSCOPED       	0x02000104	// 02000100, wbregs names: BUSSCOPED
// emmcscope compressed scope
#define	R_EMMCSCOPE       	0x02000200	// 02000200, wbregs names: EMMCSCOPE
#define	R_EMMCSCOPED      	0x02000204	// 02000200, wbregs names: EMMCSCOPED
// flashdbg compressed scope
#define	R_FLASHSCOPE      	0x02000300	// 02000300, wbregs names: FLASHSCOPE
#define	R_FLASHSCOPED     	0x02000304	// 02000300, wbregs names: FLASHSCOPED
// gatescope compressed scope
#define	R_GATESCOPE       	0x02000400	// 02000400, wbregs names: GATESCOPE
#define	R_GATESCOPED      	0x02000404	// 02000400, wbregs names: GATESCOPED
// i2cscope compressed scope
#define	R_I2CSCOPE        	0x02000500	// 02000500, wbregs names: I2CSCOPE
#define	R_I2CSCOPED       	0x02000504	// 02000500, wbregs names: I2CSCOPED
// netscope compressed scope
#define	R_NETSCOPE        	0x02000600	// 02000600, wbregs names: NETSCOPE
#define	R_NETSCOPED       	0x02000604	// 02000600, wbregs names: NETSCOPED
// routescope compressed scope
#define	R_ROUTESCOPE      	0x02000700	// 02000700, wbregs names: ROUTESCOPE
#define	R_ROUTESCOPED     	0x02000704	// 02000700, wbregs names: ROUTESCOPED
// satalscope compressed scope
#define	R_SATALSCOPE      	0x02000800	// 02000800, wbregs names: SATALSCOPE
#define	R_SATALSCOPED     	0x02000804	// 02000800, wbregs names: SATALSCOPED
// satapscope compressed scope
#define	R_SATAPSCOPE      	0x02000900	// 02000900, wbregs names: SATAPSCOPE
#define	R_SATAPSCOPED     	0x02000904	// 02000900, wbregs names: SATAPSCOPED
// satarscope compressed scope
#define	R_SATARSCOPE      	0x02000a00	// 02000a00, wbregs names: SATARSCOPE
#define	R_SATARSCOPED     	0x02000a04	// 02000a00, wbregs names: SATARSCOPED
// satatscope compressed scope
#define	R_SATATSCOPE      	0x02000b00	// 02000b00, wbregs names: SATATSCOPE
#define	R_SATATSCOPED     	0x02000b04	// 02000b00, wbregs names: SATATSCOPED
// sdioscope compressed scope
#define	R_SDIOSCOPE       	0x02000c00	// 02000c00, wbregs names: SDIOSCOPE
#define	R_SDIOSCOPED      	0x02000c04	// 02000c00, wbregs names: SDIOSCOPED
// CONSOLE registers
#define	R_CONSOLE_FIFO    	0x02000d04	// 02000d00, wbregs names: UFIFO
#define	R_CONSOLE_UARTRX  	0x02000d08	// 02000d00, wbregs names: RX
#define	R_CONSOLE_UARTTX  	0x02000d0c	// 02000d00, wbregs names: TX
// eMMC Card addresses
#define	R_EMMC_CTRL       	0x02000e00	// 02000e00, wbregs names: EMMCCARD
#define	R_EMMC_DATA       	0x02000e04	// 02000e00, wbregs names: EMMCDATA
#define	R_EMMC_FIFOA      	0x02000e08	// 02000e00, wbregs names: EMMCFIFOA, EMMCFIF0, EMMCFIFA
#define	R_EMMC_FIFOB      	0x02000e0c	// 02000e00, wbregs names: EMMCFIFOB, EMMCFIF1, EMMCFIFB
#define	R_EMMC_PHY        	0x02000e10	// 02000e00, wbregs names: EMMCPHY
// Fan registers
#define	R_FAN_FPGAPWM     	0x02000f00	// 02000f00, wbregs names: FAN_FPGAPWM
#define	R_FAN_SYSPWM      	0x02000f04	// 02000f00, wbregs names: FAN_SYSPWM
#define	R_FAN_TACH        	0x02000f08	// 02000f00, wbregs names: FAN_TACH
#define	R_FAN_TEMP        	0x02000f0c	// 02000f00, wbregs names: FAN_TEMP
#define	R_FAN             	0x02000f10	// 02000f00, wbregs names: FAN_CTRL
#define	R_FAN_OVW         	0x02000f14	// 02000f00, wbregs names: FAN_OVW, FAN_OVERRIDE
#define	R_FAN_ADDR        	0x02000f18	// 02000f00, wbregs names: FAN_ADDR, FAN_ADDRESS
#define	R_FAN_CKCOUNT     	0x02000f1c	// 02000f00, wbregs names: FANCLK, FAN_CKCOUNT
// SATA/sata control port registers
#define	R_SATA            	0x02001000	// 02001000, wbregs names: SATA
#define	R_LBALO           	0x02001004	// 02001000, wbregs names: LBALO
#define	R_LBAHI           	0x02001008	// 02001000, wbregs names: LBAHI
#define	R_SATACOUNT       	0x0200100c	// 02001000, wbregs names: SATACOUNT
#define	R_SATAPHY         	0x02001014	// 02001000, wbregs names: SATAPHY
#define	R_SATAADDR        	0x02001018	// 02001000, wbregs names: SATAADDR, SATADMA
// SDIO SD Card addresses
#define	R_SDIO_CTRL       	0x02001100	// 02001100, wbregs names: SDCARD
#define	R_SDIO_DATA       	0x02001104	// 02001100, wbregs names: SDDATA
#define	R_SDIO_FIFOA      	0x02001108	// 02001100, wbregs names: SDFIFOA, SDFIF0, SDFIFA
#define	R_SDIO_FIFOB      	0x0200110c	// 02001100, wbregs names: SDFIFOB, SDFIF1, SDFIFB
#define	R_SDIO_PHY        	0x02001110	// 02001100, wbregs names: SDPHY
// FPGA CONFIG REGISTERS: 0x4e0-0x4ff
#define	R_CFG_CRC         	0x02001200	// 02001200, wbregs names: FPGACRC
#define	R_CFG_FAR         	0x02001204	// 02001200, wbregs names: FPGAFAR
#define	R_CFG_FDRI        	0x02001208	// 02001200, wbregs names: FPGAFDRI
#define	R_CFG_FDRO        	0x0200120c	// 02001200, wbregs names: FPGAFDRO
#define	R_CFG_CMD         	0x02001210	// 02001200, wbregs names: FPGACMD
#define	R_CFG_CTL0        	0x02001214	// 02001200, wbregs names: FPGACTL0
#define	R_CFG_MASK        	0x02001218	// 02001200, wbregs names: FPGAMASK
#define	R_CFG_STAT        	0x0200121c	// 02001200, wbregs names: FPGASTAT
#define	R_CFG_LOUT        	0x02001220	// 02001200, wbregs names: FPGALOUT
#define	R_CFG_COR0        	0x02001224	// 02001200, wbregs names: FPGACOR0
#define	R_CFG_MFWR        	0x02001228	// 02001200, wbregs names: FPGAMFWR
#define	R_CFG_CBC         	0x0200122c	// 02001200, wbregs names: FPGACBC
#define	R_CFG_IDCODE      	0x02001230	// 02001200, wbregs names: FPGAIDCODE
#define	R_CFG_AXSS        	0x02001234	// 02001200, wbregs names: FPGAAXSS
#define	R_CFG_COR1        	0x02001238	// 02001200, wbregs names: FPGACOR1
#define	R_CFG_WBSTAR      	0x02001240	// 02001200, wbregs names: WBSTAR
#define	R_CFG_TIMER       	0x02001244	// 02001200, wbregs names: CFGTIMER
#define	R_CFG_BOOTSTS     	0x02001258	// 02001200, wbregs names: BOOTSTS
#define	R_CFG_CTL1        	0x02001260	// 02001200, wbregs names: FPGACTL1
#define	R_CFG_BSPI        	0x0200127c	// 02001200, wbregs names: FPGABSPI
// CPU Net Controller registers
#define	R_CPUNET          	0x02001300	// 02001300, wbregs names: CPUNET
#define	R_CPUNETMAC1      	0x02001304	// 02001300, wbregs names: CPUMAC1
#define	R_CPUNETMAC2      	0x02001308	// 02001300, wbregs names: CPUMAC2
#define	R_CPUNETIPV4      	0x0200130c	// 02001300, wbregs names: CPUIPV4
#define	R_CPUNETIPV6P1    	0x02001310	// 02001300, wbregs names: CPUIP6P1
#define	R_CPUNETIPV6P2    	0x02001314	// 02001300, wbregs names: CPUIP6P2
#define	R_CPUNETIPV6P3    	0x02001318	// 02001300, wbregs names: CPUIP6P3
#define	R_CPUNETIPV6P4    	0x0200131c	// 02001300, wbregs names: CPUIP6P4
#define	R_CPUNETRXDROPS   	0x02001320	// 02001300, wbregs names: RXDROPS
#define	R_CPUNETRXPKTS    	0x02001324	// 02001300, wbregs names: RXPKTS
#define	R_CPUNETTXPKTS    	0x02001328	// 02001300, wbregs names: TXPKTS
#define	R_CPUNETTX_BASE   	0x02001340	// 02001300, wbregs names: CNTXBASE, CPUNETTXBASE
#define	R_CPUNETTX_LEN    	0x02001344	// 02001300, wbregs names: CNTXLEN, CPUNETTXLEN
#define	R_CPUNETTX_RPTR   	0x02001348	// 02001300, wbregs names: CNTXRPTR, CPUNETTXRPTR
#define	R_CPUNETTX_WPTR   	0x0200134c	// 02001300, wbregs names: CNTXWPTR, CPUNETTXWPTR
#define	R_CPUNETRX_BASE   	0x02001350	// 02001300, wbregs names: CNRXBASE, CPUNETRXBASE
#define	R_CPUNETRX_LEN    	0x02001354	// 02001300, wbregs names: CNRXLEN, CPUNETRXLEN
#define	R_CPUNETRX_RPTR   	0x02001358	// 02001300, wbregs names: CNRXRPTR, CPUNETRXRPTR
#define	R_CPUNETRX_WPTR   	0x0200135c	// 02001300, wbregs names: CNRXWPTR, CPUNETRXWPTR
#define	R_CPUNETRX_DBG    	0x02001360	// 02001300, wbregs names: CNRXDBG, CPUNETRXDBG
#define	R_CPUNETTX_DBG    	0x02001364	// 02001300, wbregs names: CNTXDBG, CPUNETTXDBG
// I2C Controller registers
#define	R_I2CCPU          	0x02001400	// 02001400, wbregs names: I2CCPU, I2CCPU_CTRL, I2CCPUCTRL
#define	R_I2CCPU_OVW      	0x02001404	// 02001400, wbregs names: I2CCPU_OVW, I2CCPU_OVERRIDE
#define	R_I2CCPU_ADDR     	0x02001408	// 02001400, wbregs names: I2CCPU_ADDR, I2CCPU_ADDRESS
#define	R_I2CCPU_CKCOUNT  	0x0200140c	// 02001400, wbregs names: I2CCPUCLK, I2CCPU_CKCOUNT
#define	R_I2CDMA          	0x02001410	// 02001410, wbregs names: I2CDMA
#define	R_I2CDMA_ADDR     	0x02001414	// 02001410, wbregs names: I2CDMAADDR
#define	R_I2CDMA_BASE     	0x02001418	// 02001410, wbregs names: I2CDMABASE
#define	R_I2CDMA_LEN      	0x0200141c	// 02001410, wbregs names: I2CDMALEN
#define	R_RXNETCK0        	0x02001420	// 02001420, wbregs names: RXNETCLK0, RXNETCK0
#define	R_RXNETCK1        	0x02001424	// 02001420, wbregs names: RXNETCLK1, RXNETCK1
#define	R_RXNETCK2        	0x02001428	// 02001420, wbregs names: RXNETCLK2, RXNETCK2
#define	R_RXNETCK3        	0x0200142c	// 02001420, wbregs names: RXNETCLK3, RXNETCK3
#define	R_TXNETCLK        	0x02001430	// 02001420, wbregs names: TXNETCLK
#define	R_BUILDTIME       	0x02001440	// 02001440, wbregs names: BLDTIME, BUILDTIME
#define	R_GPIO            	0x02001444	// 02001444, wbregs names: GPIO, GPI, GPO
#define	R_NETDBG          	0x02001448	// 02001448, wbregs names: NETDBG
#define	R_NETLOCK         	0x0200144c	// 0200144c, wbregs names: NETLOCK
#define	R_NETRESET        	0x02001450	// 02001450, wbregs names: NETRESET
#define	R_PWRCOUNT        	0x02001454	// 02001454, wbregs names: PWRCOUNT
#define	R_RTCCOUNT        	0x02001458	// 02001458, wbregs names: RTCCOUNT
#define	R_SATAREF         	0x0200145c	// 0200145c, wbregs names: SATAREF
#define	R_SATARX          	0x02001460	// 02001460, wbregs names: SATARX, SATARXCLK, SATARXCK
#define	R_SATATX          	0x02001464	// 02001464, wbregs names: SATATX, SATATXCLK, SATATXCK
#define	R_SICLKFREQ       	0x02001468	// 02001468, wbregs names: SICLKFREQ
#define	R_SIREFCLK        	0x0200146c	// 0200146c, wbregs names: SIREFCLK
#define	R_SIREFFREQ       	0x02001470	// 02001470, wbregs names: SIREFFREQ
#define	R_SPIO            	0x02001474	// 02001474, wbregs names: SPIO
#define	R_VERSION         	0x02001478	// 02001478, wbregs names: VERSION
#define	R_ROUTER          	0x02001500	// 02001500, wbregs names: ROUTER
#define	R_ROUTER0         	0x02001500	// 02001500, wbregs names: ROUTER0
#define	R_ROUTERSZ0       	0x02001504	// 02001500, wbregs names: ROUTERSZ0
#define	R_ROUTERWR0       	0x02001508	// 02001500, wbregs names: ROUTERWR0
#define	R_ROUTERRD0       	0x0200150c	// 02001500, wbregs names: ROUTERRD0
#define	R_ROUTER1         	0x02001510	// 02001500, wbregs names: ROUTER1
#define	R_ROUTERSZ1       	0x02001514	// 02001500, wbregs names: ROUTERSZ1
#define	R_ROUTERWR1       	0x02001518	// 02001500, wbregs names: ROUTERWR1
#define	R_ROUTERRD1       	0x0200151c	// 02001500, wbregs names: ROUTERRD1
#define	R_ROUTER2         	0x02001520	// 02001500, wbregs names: ROUTER2
#define	R_ROUTERSZ2       	0x02001524	// 02001500, wbregs names: ROUTERSZ2
#define	R_ROUTERWR2       	0x02001528	// 02001500, wbregs names: ROUTERWR2
#define	R_ROUTERRD2       	0x0200152c	// 02001500, wbregs names: ROUTERRD2
#define	R_ROUTER3         	0x02001530	// 02001500, wbregs names: ROUTER3
#define	R_ROUTERSZ3       	0x02001534	// 02001500, wbregs names: ROUTERSZ3
#define	R_ROUTERWR3       	0x02001538	// 02001500, wbregs names: ROUTERWR3
#define	R_ROUTERRD3       	0x0200153c	// 02001500, wbregs names: ROUTERRD3
#define	R_ROUTERPK0       	0x02001540	// 02001500, wbregs names: ROUTERPK0
#define	R_ROUTERBY0       	0x02001544	// 02001500, wbregs names: ROUTERBY0
#define	R_ROUTERFP0       	0x02001548	// 02001500, wbregs names: ROUTERFP0
#define	R_ROUTERFB0       	0x0200154c	// 02001500, wbregs names: ROUTERFB0
#define	R_ROUTERPK1       	0x02001550	// 02001500, wbregs names: ROUTERPK1
#define	R_ROUTERBY1       	0x02001554	// 02001500, wbregs names: ROUTERBY1
#define	R_ROUTERFP1       	0x02001558	// 02001500, wbregs names: ROUTERFP1
#define	R_ROUTERFB1       	0x0200155c	// 02001500, wbregs names: ROUTERFB1
#define	R_ROUTERPK2       	0x02001560	// 02001500, wbregs names: ROUTERPK2
#define	R_ROUTERBY2       	0x02001564	// 02001500, wbregs names: ROUTERBY2
#define	R_ROUTERFP2       	0x02001568	// 02001500, wbregs names: ROUTERFP2
#define	R_ROUTERFB2       	0x0200156c	// 02001500, wbregs names: ROUTERFB2
#define	R_ROUTERPK3       	0x02001570	// 02001500, wbregs names: ROUTERPK3
#define	R_ROUTERBY3       	0x02001574	// 02001500, wbregs names: ROUTERBY3
#define	R_ROUTERFP3       	0x02001578	// 02001500, wbregs names: ROUTERFP3
#define	R_ROUTERFB3       	0x0200157c	// 02001500, wbregs names: ROUTERFB3
#define	R_ROUTERNWH0      	0x02001580	// 02001500, wbregs names: ROUTERNWH0
#define	R_ROUTERNWL0      	0x02001584	// 02001500, wbregs names: ROUTERNWL0
#define	R_ROUTERLKH0      	0x02001588	// 02001500, wbregs names: ROUTERLKH0
#define	R_ROUTERLKL0      	0x0200158c	// 02001500, wbregs names: ROUTERLKL0
#define	R_ROUTERNWH1      	0x02001590	// 02001500, wbregs names: ROUTERNWH1
#define	R_ROUTERNWL1      	0x02001594	// 02001500, wbregs names: ROUTERNWL1
#define	R_ROUTERLKH1      	0x02001598	// 02001500, wbregs names: ROUTERLKH1
#define	R_ROUTERLKL1      	0x0200159c	// 02001500, wbregs names: ROUTERLKL1
#define	R_ROUTERNWH2      	0x020015a0	// 02001500, wbregs names: ROUTERNWH2
#define	R_ROUTERNWL2      	0x020015a4	// 02001500, wbregs names: ROUTERNWL2
#define	R_ROUTERLKH2      	0x020015a8	// 02001500, wbregs names: ROUTERLKH2
#define	R_ROUTERLKL2      	0x020015ac	// 02001500, wbregs names: ROUTERLKL2
#define	R_ROUTERNWH3      	0x020015b0	// 02001500, wbregs names: ROUTERNWH3
#define	R_ROUTERNWL3      	0x020015b4	// 02001500, wbregs names: ROUTERNWL3
#define	R_ROUTERLKH3      	0x020015b8	// 02001500, wbregs names: ROUTERLKH3
#define	R_ROUTERLKL3      	0x020015bc	// 02001500, wbregs names: ROUTERLKL3
#define	R_ROUTERNWH4      	0x020015c0	// 02001500, wbregs names: ROUTERNWH4
#define	R_ROUTERNWL4      	0x020015c4	// 02001500, wbregs names: ROUTERNWL4
#define	R_ROUTERLKH4      	0x020015c8	// 02001500, wbregs names: ROUTERLKH4
#define	R_ROUTERLKL4      	0x020015cc	// 02001500, wbregs names: ROUTERLKL4
#define	R_ROUTERDBG0      	0x020015d0	// 02001500, wbregs names: ROUTERDBG0
#define	R_ROUTERDBG1      	0x020015d4	// 02001500, wbregs names: ROUTERDBG1
#define	R_ROUTERDBG2      	0x020015d8	// 02001500, wbregs names: ROUTERDBG2
#define	R_ROUTERDBG3      	0x020015dc	// 02001500, wbregs names: ROUTERDBG3
#define	R_ROUTERDBG4      	0x020015e0	// 02001500, wbregs names: ROUTERDBG4
#define	R_ROUTERNEVER     	0x020015e8	// 02001500, wbregs names: ROUTERNV, RTNEVER
#define	R_ROUTERALWAYS    	0x020015ec	// 02001500, wbregs names: ROUTERAL, RTALWAYS
#define	R_ROUTERDBGS      	0x020015fc	// 02001500, wbregs names: ROUTERDBGS
#define	R_DDR3_PHY        	0x02001600	// 02001600, wbregs names: DDR3_PHY, DPHYSTAT0
#define	R_DDR3_PHYSTAT1   	0x02001604	// 02001600, wbregs names: DDR3_PHYSTAT1, DPHYSTAT1
#define	R_DDR3_PHYSTAT2   	0x02001608	// 02001600, wbregs names: DDR3_PHYSTAT2, DPHYSTAT2
#define	R_DDR3_PHYSTAT3   	0x0200160c	// 02001600, wbregs names: DDR3_PHYSTAT3, DPHYSTAT3
#define	R_DDR3_PHYCTRLSTAT	0x02001610	// 02001600, wbregs names: DDR3_PHYCTRLSTAT, DCTRLSTAT
#define	R_DDR3_PHYRESET   	0x02001644	// 02001600, wbregs names: DDR3_PHYRESET, DCTRLRESET
#define	R_DDR3_PHYDBGSEL  	0x0200164c	// 02001600, wbregs names: DDR3_PHYDBGSEL, DCTRLDBG
#define	R_NETSTAT         	0x02001800	// 02001800, wbregs names: NETSTAT
// SATA DRP/satadrp control port registers
#define	R_PLLDRP          	0x02002000	// 02002000, wbregs names: PLLDRP
#define	R_GTXDRP          	0x02002800	// 02002000, wbregs names: GTXDRP
#define	R_BKRAM           	0x04000000	// 04000000, wbregs names: RAM
#define	R_FLASH           	0x06000000	// 06000000, wbregs names: FLASH
#define	R_DDR3_CONTROLLER 	0x40000000	// 40000000, wbregs names: DDR3_CONTROLLER, DDR3, SDRAM
// ZipCPU control/debug registers
#define	R_ZIPCTRL         	0x80000000	// 80000000, wbregs names: CPU, ZIPCTRL
#define	R_ZIPREGS         	0x80000080	// 80000000, wbregs names: ZIPREGS
#define	R_ZIPS0           	0x80000080	// 80000000, wbregs names: SR0
#define	R_ZIPS1           	0x80000084	// 80000000, wbregs names: SR1
#define	R_ZIPS2           	0x80000088	// 80000000, wbregs names: SR2
#define	R_ZIPS3           	0x8000008c	// 80000000, wbregs names: SR3
#define	R_ZIPS4           	0x80000090	// 80000000, wbregs names: SR4
#define	R_ZIPS5           	0x80000094	// 80000000, wbregs names: SR5
#define	R_ZIPS6           	0x80000098	// 80000000, wbregs names: SR6
#define	R_ZIPS7           	0x8000009c	// 80000000, wbregs names: SR7
#define	R_ZIPS8           	0x800000a0	// 80000000, wbregs names: SR8
#define	R_ZIPS9           	0x800000a4	// 80000000, wbregs names: SR9
#define	R_ZIPS10          	0x800000a8	// 80000000, wbregs names: SR10
#define	R_ZIPS11          	0x800000ac	// 80000000, wbregs names: SR11
#define	R_ZIPS12          	0x800000b0	// 80000000, wbregs names: SR12
#define	R_ZIPSSP          	0x800000b4	// 80000000, wbregs names: SSP, SR13
#define	R_ZIPCC           	0x800000b8	// 80000000, wbregs names: ZIPCC, CC, SCC, SR14
#define	R_ZIPPC           	0x800000bc	// 80000000, wbregs names: ZIPPC, PC, SPC, SR15
#define	R_ZIPUSER         	0x800000c0	// 80000000, wbregs names: ZIPUSER
#define	R_ZIPU0           	0x800000c0	// 80000000, wbregs names: UR0
#define	R_ZIPU1           	0x800000c4	// 80000000, wbregs names: UR1
#define	R_ZIPU2           	0x800000c8	// 80000000, wbregs names: UR2
#define	R_ZIPU3           	0x800000cc	// 80000000, wbregs names: UR3
#define	R_ZIPU4           	0x800000d0	// 80000000, wbregs names: UR4
#define	R_ZIPU5           	0x800000d4	// 80000000, wbregs names: UR5
#define	R_ZIPU6           	0x800000d8	// 80000000, wbregs names: UR6
#define	R_ZIPU7           	0x800000dc	// 80000000, wbregs names: UR7
#define	R_ZIPU8           	0x800000e0	// 80000000, wbregs names: UR8
#define	R_ZIPU9           	0x800000e4	// 80000000, wbregs names: UR9
#define	R_ZIPU10          	0x800000e8	// 80000000, wbregs names: UR10
#define	R_ZIPU11          	0x800000ec	// 80000000, wbregs names: UR11
#define	R_ZIPU12          	0x800000f0	// 80000000, wbregs names: UR12, UFP
#define	R_ZIPUSP          	0x800000f4	// 80000000, wbregs names: USP, UR13
#define	R_ZIPUCC          	0x800000f8	// 80000000, wbregs names: ZIPUCC, UCC
#define	R_ZIPUPC          	0x800000fc	// 80000000, wbregs names: ZIPUPC, UPC
#define	R_ZIPSYSTEM       	0x80000100	// 80000000, wbregs names: ZIPSYSTEM, ZIPSYS
#define	R_ZIPPIC          	0x80000100	// 80000000, wbregs names: ZIPPIC
#define	R_ZIPWDOG         	0x80000104	// 80000000, wbregs names: ZIPWDOG
#define	R_ZIPBDOG         	0x80000108	// 80000000, wbregs names: ZIPBDOG
#define	R_ZIPAPIC         	0x8000010c	// 80000000, wbregs names: ZIPAPIC
#define	R_ZIPTIMA         	0x80000110	// 80000000, wbregs names: ZIPTIMA
#define	R_ZIPTIMB         	0x80000114	// 80000000, wbregs names: ZIPTIMB
#define	R_ZIPTIMC         	0x80000118	// 80000000, wbregs names: ZIPTIMC
#define	R_ZIPJIFF         	0x8000011c	// 80000000, wbregs names: ZIPJIFF
#define	R_ZIPMTASK        	0x80000120	// 80000000, wbregs names: ZIPMTASK
#define	R_ZIPMMSTL        	0x80000124	// 80000000, wbregs names: ZIPMMSTL
#define	R_ZIPMPSTL        	0x80000128	// 80000000, wbregs names: ZIPMPSTL
#define	R_ZIPMINSN        	0x8000012c	// 80000000, wbregs names: ZIPMINSN
#define	R_ZIPUTASK        	0x80000130	// 80000000, wbregs names: ZIPUTASK
#define	R_ZIPUMSTL        	0x80000134	// 80000000, wbregs names: ZIPUMSTL
#define	R_ZIPUPSTL        	0x80000138	// 80000000, wbregs names: ZIPUPSTL
#define	R_ZIPUINSN        	0x8000013c	// 80000000, wbregs names: ZIPUINSN
#define	R_ZIPDMAC         	0x80000140	// 80000000, wbregs names: ZIPDMAC


//
// The @REGDEFS.H.DEFNS tag
//
// @REGDEFS.H.DEFNS for masters
#define	BAUDRATE	1000000
// @REGDEFS.H.DEFNS for peripherals
#define	FLASHBASE	0x06000000
#define	FLASHLEN	0x02000000
#define	FLASHLGLEN	25
//
#define	FLASH_RDDELAY	3
#define	FLASH_NDUMMY	8
//
#define	BKRAMBASE	0x04000000
#define	BKRAMLEN	0x00080000
#define	DDR3_CONTROLLERBASE	0x40000000
#define	DDR3_CONTROLLERLEN	0x40000000
// @REGDEFS.H.DEFNS at the top level
// End of definitions from REGDEFS.H.DEFNS
//
// The @REGDEFS.H.INSERT tag
//
// @REGDEFS.H.INSERT for masters
// @REGDEFS.H.INSERT for peripherals
// Flash control constants
#define	QSPI_FLASH	// This core and hardware support a Quad SPI flash
#define	SZPAGEB		256			// Bytes in a page
#define	PGLENB		256
#define	SZPAGEW		64			// 32b words in a page
#define	PGLENW		64
#define	NPAGES		256			// Pages per sector
#define	SECTORSZB	(NPAGES * SZPAGEB)	// In bytes, not words!!
#define	SECTORSZW	(NPAGES * SZPAGEW)	// In words
#define	NSECTORS	((1 << FLASHLGLEN)/SECTORSZB)
#define	SECTOROF(A)	((A) & (-1<<16))
#define	SUBSECTOROF(A)	((A) & (-1<<12))
#define	PAGEOF(A)	((A) & (-1<<8))
#define	FLASHSZ		FLASHLEN

////////////////////////////////////////////////////////////////////////////////
//
// ZipCPU register definitions
// {{{

#define	CPU_GO		0x0000
#define	CPU_HALT	0x0001
#define	CPU_STALL	0x0002
#define	CPU_STEP	0x0004
#define	CPU_RESET	0x0008
#define	CPU_CLRCACHE	0x0010
// (Reserved)		0x00e0
#define	CPU_SLEEPING	0x0100
#define	CPU_GIE		0x0200
#define	CPU_INT		0x0400
#define	CPU_BREAK	0x0800
#define	CPU_EXINT	0xfffff000
//
#define	CPU_sR0		0x0020
#define	CPU_sSP		0x002d
#define	CPU_sCC		0x002e
#define	CPU_sPC		0x002f
#define	CPU_uR0		0x0030
#define	CPU_uSP		0x003d
#define	CPU_uCC		0x003e
#define	CPU_uPC		0x003f

#ifdef	BKROM_ACCESS
#define	RESET_ADDRESS	@$[0x%08x](bkrom.REGBASE)
#else
#ifdef	FLASH_ACCESS
#define	RESET_ADDRESS	0x06e00000
#else
#define	RESET_ADDRESS	0x04000000
#endif	// FLASH_ACCESS
#endif	// BKROM_ACCESS
// }}}
// @REGDEFS.H.INSERT from the top level
typedef	struct {
	unsigned	m_addr;
	const char	*m_name;
} REGNAME;

extern	const	REGNAME	*bregs;
extern	const	int	NREGS;
// #define	NREGS	(sizeof(bregs)/sizeof(bregs[0]))

extern	unsigned	addrdecode(const char *v);
extern	const	char *addrname(const unsigned v);
// End of definitions from REGDEFS.H.INSERT


#endif	// REGDEFS_H
